export const WORKFLOW_TEST_PAGE_HTML = '<!doctype html>'
  + '<html lang=zh-CN>'
  + '<head>'
  + '<meta charset=utf-8>'
  + '<meta name=viewport content=width=device-width,initial-scale=1>'
  + '<title>Workflow Test</title>'
  + '<style>body{font-family:sans-serif;margin:24px}textarea,input,button{font:inherit}textarea,input{width:100%;box-sizing:border-box;padding:8px;margin:6px 0}textarea{min-height:220px}button{padding:8px 12px;margin:6px 6px 0 0}pre{background:#111;color:#d8f5e4;padding:12px;white-space:pre-wrap;min-height:260px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:900px){.grid{grid-template-columns:1fr}}</style>'
  + '</head>'
  + '<body>'
  + '<h1>Workflow 测试页</h1>'
  + '<p>测试 /workflows/start、/workflows/approval/resume、/workflows/:id</p>'
  + '<div class=grid>'
  + '<section><h2>启动</h2><label>Start Payload JSON</label><textarea id=startPayload>{\n  "workflowName": "inspection-rectification",\n  "input": {\n    "inspectionId": "INS-2024-005",\n    "area": "临时用电区域",\n    "assignee": "赵工",\n    "deadline": "2026-04-20 12:00",\n    "severity": "high",\n    "issues": ["配电箱门未关闭", "电缆拖地未架空"],\n    "simulateNotificationFailure": false\n  }\n}</textarea><div><button id=startBtn>启动流程</button><button id=refreshBtn>刷新快照</button></div><label>instanceId</label><input id=instanceId><label>approvalRequestId</label><input id=approvalRequestId><label>actor</label><input id=actor value=site-manager><label>comment</label><input id=comment value=同意整改，立即执行><div><button id=approveBtn>审批通过</button><button id=rejectBtn>审批驳回</button></div><pre id=statusBox>等待操作。</pre></section>'
  + '<section><h2>快照</h2><pre id=snapshotBox>尚未获取流程快照。</pre></section>'
  + '</div>'
  + '<script>'
  + 'const $=id=>document.getElementById(id);'
  + 'const els={startPayload:$(\'startPayload\'),instanceId:$(\'instanceId\'),approvalRequestId:$(\'approvalRequestId\'),actor:$(\'actor\'),comment:$(\'comment\'),statusBox:$(\'statusBox\'),snapshotBox:$(\'snapshotBox\')};'
  + 'const setStatus=t=>els.statusBox.textContent=t;'
  + 'const sync=s=>{els.snapshotBox.textContent=JSON.stringify(s,null,2);if(s&&s.instance&&s.instance.id)els.instanceId.value=s.instance.id;const p=Array.isArray(s&&s.approvals)?s.approvals.find(x=>x.status===\'pending\'):null;if(p)els.approvalRequestId.value=p.id;};'
  + 'async function req(url,opt){const r=await fetch(url,Object.assign({headers:{[\'Content-Type\']:\'application/json\'}},opt||{}));const t=await r.text();const d=t?JSON.parse(t):null;if(!r.ok)throw new Error((d&&d.error)||(\'HTTP \'+r.status));return d;}'
  + 'async function start(){try{setStatus(\'正在启动流程...\');const payload=JSON.parse(els.startPayload.value);const s=await req(\'/workflows/start\',{method:\'POST\',body:JSON.stringify(payload)});sync(s);setStatus(\'流程已启动，当前状态: \'+s.instance.status);}catch(e){setStatus(\'启动失败: \'+e.message);}}'
  + 'async function refresh(){try{const id=els.instanceId.value.trim();if(!id)throw new Error(\'请先填写 instanceId\');setStatus(\'正在刷新流程快照...\');const s=await req(\'/workflows/\'+encodeURIComponent(id));sync(s);setStatus(\'刷新成功，当前状态: \'+s.instance.status);}catch(e){setStatus(\'刷新失败: \'+e.message);}}'
  + 'async function resume(approved){try{const approvalRequestId=els.approvalRequestId.value.trim();if(!approvalRequestId)throw new Error(\'请先填写 approvalRequestId\');setStatus(\'正在提交审批...\');const s=await req(\'/workflows/approval/resume\',{method:\'POST\',body:JSON.stringify({approvalRequestId,approved,actor:els.actor.value.trim(),comment:els.comment.value.trim()})});sync(s);setStatus(\'审批完成，当前状态: \'+s.instance.status);}catch(e){setStatus(\'审批失败: \'+e.message);}}'
  + '$(\'startBtn\').addEventListener(\'click\',start);$(\'refreshBtn\').addEventListener(\'click\',refresh);$(\'approveBtn\').addEventListener(\'click\',()=>resume(true));$(\'rejectBtn\').addEventListener(\'click\',()=>resume(false));'
  + '</script>'
  + '</body>'
  + '</html>';
